// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: api/features/features.proto

package features

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Gpu provides parameters for the GPU feature
type Gpu struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Gpu) Reset() {
	*x = Gpu{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_features_features_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gpu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gpu) ProtoMessage() {}

func (x *Gpu) ProtoReflect() protoreflect.Message {
	mi := &file_api_features_features_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gpu.ProtoReflect.Descriptor instead.
func (*Gpu) Descriptor() ([]byte, []int) {
	return file_api_features_features_proto_rawDescGZIP(), []int{0}
}

// Boosted provides parameters for the boosted feature (vertical scalability).
type Boosted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Boosted) Reset() {
	*x = Boosted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_features_features_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Boosted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Boosted) ProtoMessage() {}

func (x *Boosted) ProtoReflect() protoreflect.Message {
	mi := &file_api_features_features_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Boosted.ProtoReflect.Descriptor instead.
func (*Boosted) Descriptor() ([]byte, []int) {
	return file_api_features_features_proto_rawDescGZIP(), []int{1}
}

type Feature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Feature:
	//
	//	*Feature_Gpu
	//	*Feature_Boosted
	Feature isFeature_Feature `protobuf_oneof:"feature"`
	// If true, this feature is required for the repl to be acquired.
	// If false or unset, this feature is optional and the server can fall back to
	// a sensible default if the feature can not be enabled.
	Required bool `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
}

func (x *Feature) Reset() {
	*x = Feature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_features_features_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Feature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Feature) ProtoMessage() {}

func (x *Feature) ProtoReflect() protoreflect.Message {
	mi := &file_api_features_features_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Feature.ProtoReflect.Descriptor instead.
func (*Feature) Descriptor() ([]byte, []int) {
	return file_api_features_features_proto_rawDescGZIP(), []int{2}
}

func (m *Feature) GetFeature() isFeature_Feature {
	if m != nil {
		return m.Feature
	}
	return nil
}

func (x *Feature) GetGpu() *Gpu {
	if x, ok := x.GetFeature().(*Feature_Gpu); ok {
		return x.Gpu
	}
	return nil
}

func (x *Feature) GetBoosted() *Boosted {
	if x, ok := x.GetFeature().(*Feature_Boosted); ok {
		return x.Boosted
	}
	return nil
}

func (x *Feature) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

type isFeature_Feature interface {
	isFeature_Feature()
}

type Feature_Gpu struct {
	// The GPU feature provides the repl with at least one partition of an A100
	// GPU. This allows usage of CUDA to optimize AI and other GPU-enhanced
	// workloads.
	Gpu *Gpu `protobuf:"bytes,1,opt,name=gpu,proto3,oneof"`
}

type Feature_Boosted struct {
	// The Boosted feature provides the repl with a guaranteed reservation of
	// CPU and Memory instead of overcommitting.
	Boosted *Boosted `protobuf:"bytes,2,opt,name=boosted,proto3,oneof"`
}

func (*Feature_Gpu) isFeature_Feature() {}

func (*Feature_Boosted) isFeature_Feature() {}

var File_api_features_features_proto protoreflect.FileDescriptor

var file_api_features_features_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2f, 0x66,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x72,
	0x65, 0x70, 0x6c, 0x69, 0x74, 0x2e, 0x67, 0x6f, 0x76, 0x61, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x22, 0x05, 0x0a, 0x03, 0x47, 0x70, 0x75, 0x22,
	0x09, 0x0a, 0x07, 0x42, 0x6f, 0x6f, 0x73, 0x74, 0x65, 0x64, 0x22, 0xa4, 0x01, 0x0a, 0x07, 0x46,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x32, 0x0a, 0x03, 0x67, 0x70, 0x75, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x74, 0x2e, 0x67, 0x6f, 0x76,
	0x61, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e,
	0x47, 0x70, 0x75, 0x48, 0x00, 0x52, 0x03, 0x67, 0x70, 0x75, 0x12, 0x3e, 0x0a, 0x07, 0x62, 0x6f,
	0x6f, 0x73, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x72, 0x65,
	0x70, 0x6c, 0x69, 0x74, 0x2e, 0x67, 0x6f, 0x76, 0x61, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x66,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x42, 0x6f, 0x6f, 0x73, 0x74, 0x65, 0x64, 0x48,
	0x00, 0x52, 0x07, 0x62, 0x6f, 0x6f, 0x73, 0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65,
	0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x65,
	0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x72, 0x65, 0x70, 0x6c, 0x69, 0x74, 0x2f, 0x67, 0x6f, 0x76, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_features_features_proto_rawDescOnce sync.Once
	file_api_features_features_proto_rawDescData = file_api_features_features_proto_rawDesc
)

func file_api_features_features_proto_rawDescGZIP() []byte {
	file_api_features_features_proto_rawDescOnce.Do(func() {
		file_api_features_features_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_features_features_proto_rawDescData)
	})
	return file_api_features_features_proto_rawDescData
}

var file_api_features_features_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_features_features_proto_goTypes = []interface{}{
	(*Gpu)(nil),     // 0: replit.goval.api.features.Gpu
	(*Boosted)(nil), // 1: replit.goval.api.features.Boosted
	(*Feature)(nil), // 2: replit.goval.api.features.Feature
}
var file_api_features_features_proto_depIdxs = []int32{
	0, // 0: replit.goval.api.features.Feature.gpu:type_name -> replit.goval.api.features.Gpu
	1, // 1: replit.goval.api.features.Feature.boosted:type_name -> replit.goval.api.features.Boosted
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_features_features_proto_init() }
func file_api_features_features_proto_init() {
	if File_api_features_features_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_features_features_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gpu); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_features_features_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Boosted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_features_features_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Feature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_features_features_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Feature_Gpu)(nil),
		(*Feature_Boosted)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_features_features_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_features_features_proto_goTypes,
		DependencyIndexes: file_api_features_features_proto_depIdxs,
		MessageInfos:      file_api_features_features_proto_msgTypes,
	}.Build()
	File_api_features_features_proto = out.File
	file_api_features_features_proto_rawDesc = nil
	file_api_features_features_proto_goTypes = nil
	file_api_features_features_proto_depIdxs = nil
}
